uni/views/admin.py
from functools import wraps
from flask import Blueprint, render_template, g, abort, request, session
from flask import redirect, url_for
from uni.domain import API as DomainAPI
from uni.invoice import API as InvoiceAPI
from uni.user import API as UserAPI
from uni.hosting import API as HostingAPI

bp = Blueprint('admin', __name__, url_prefix='/admin')
hosting_api = HostingAPI()
domain_api = DomainAPI()
invoice_api = InvoiceAPI()
user_api = UserAPI()


def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        user = g.user
        if user is None or user.group != 'admin':
            abort(404)
        else:
            return f(*args, **kwargs)
    return decorated_function


@bp.route('/')
@admin_required
def index():
    pending_domains = domain_api.get_pending()
    monthly_sales = invoice_api.get_monthly_sales()
    total_sales = sum([monthly_sale['amount']
                       for monthly_sale in monthly_sales])
    return render_template('admin/index.html',
                           monthly_sales=monthly_sales,
                           pending_domains=pending_domains,
                           total_sales=total_sales)


@bp.route('/users/', methods=["GET", "POST"])
@admin_required
def users():
    searched_users = None
    if 'search' in request.form:
        username = request.form['username']
        searched_users = user_api.search_user(username)

    if 'login_as_id' in request.args:
        login_as_id = long(request.args['login_as_id'])
        login_as_username = request.args['login_as_username']
        session['login_as'] = {
            'user_id': login_as_id,
            'username': login_as_username,
        }
        return redirect(url_for('user.index'))
    return render_template('admin/users.html',
                           searched_users=searched_users)


@bp.route('/users/<id>/', methods=["GET", "POST"])
@admin_required
def users_show(id):
    user_id = long(id)
    if 'delete-hosting' in request.form:
        hosting_id = long(request.form['delete-hosting'])
        hosting_api.delete(user_id, hosting_id)
    hostings = hosting_api.get_all(user_id)
    return render_template('admin/users_show.html',
                           hostings=hostings)

uni/views/user/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint, flash, request, redirect, url_for
from flask import g, render_template
from flask.ext.login import login_required, login_user, logout_user
from flask.ext.babel import gettext as _
from uni import user, invoice, login_manager
from uni.tasks import send_email
from uni.forms import SignupForm, LoginForm, PasswordChangeForm

bp = Blueprint('user', __name__, url_prefix='/user')
user_api = user.API()
invoice_api = invoice.API()


@login_manager.user_loader
def load_user(user_id):
    return user_api.load_user(user_id)


@bp.route('/')
@login_required
def index():
    username = g.user.username
    unpaid_invoices = invoice_api.get_unpaid_invoices_by_user(username)
    return render_template('user/index.html',
                           unpaid_invoices=unpaid_invoices)


@bp.route('/login', methods=["GET", "POST"])
def login():
    if g.user is not None:
        return redirect("https://%s%s" % (request.host, url_for("user.index")))

    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember_me = form.remember_me.data

        user = user_api.validate(username, password)
        if user:
            login_user(user_api.load_user(user['id']), remember=remember_me)
            return redirect(request.args.get("next") or "https://%s%s" %
                            (request.host, url_for("user.index")))
        else:
            flash('Failed login', 'error')

    return render_template('user/login.html',
                           form=form)


@bp.route('/signup', methods=["GET", "POST"])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = user_api.get_by_username(username)
        if user:
            flash("Username already exists", "error")
        else:
            user = user_api.create(username, password)
            login_user(user_api.load_user(user['id']))
            return redirect("https://%s%s" %
                            (request.host, url_for("user.index")))

    return render_template('user/signup.html',
                           form=form)


@bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(request.args.get("next") or "http://%s%s" %
                    (request.host, url_for("index")))


@bp.route("/invoices/")
@login_required
def invoices():
    username = g.user.username
    invoices = invoice_api.get_invoices_by_user(username)
    return render_template("user/invoices.html",
                           invoices=invoices)


@bp.route("/invoices/<invoice_id>")
@login_required
def invoices_show(invoice_id):
    invoice_id = int(invoice_id)
    username = g.user.username
    invoice = invoice_api.validate_by_user(username, invoice_id)
    if not invoice:
        return redirect(url_for("user.invoices"))

    invoice_items = invoice_api.get_items_by_invoice_id(invoice_id)
    total_amount = 0
    for invoice_item in invoice_items:
        total_amount += invoice_item['amount']
    return render_template("user/invoices_show.html",
                           total_amount=total_amount,
                           invoice_items=invoice_items,
                           invoice=invoice)


@bp.route("/password", methods=["GET", "POST"])
@login_required
def password():
    username = g.user.username
    message = ''
    form = PasswordChangeForm()
    if form.validate_on_submit():
        original_password = request.form['original_password']
        new_password = form.password.data
        message = user_api.change_password(username,
                                           original_password,
                                           new_password)
    return render_template("user/password.html",
                           message=message,
                           form=form)


@bp.route("/pwreset/", methods=["GET", "POST"])
def pwreset():
    email = ''
    message = ''
    response = ''
    if 'submit' in request.form:
        email = request.form['email']
        user = user_api.get_by_username(email)
        if user:
            token = user_api.create_pwreset_token(user['id'])
            subject = _("password reset - yiduoyun")
            recipients = [email]
            url = "https://%s%s%s" % (request.host,
                                      url_for("user.pwreset"),
                                      token)
            body = "<p>%s,</p>" % _("Dear Customer")
            body += "<p>%s</p>" % _("You submitted a password reset request "
                                    "recently. If you did not, please ignore "
                                    "this meesage. If you do, please click "
                                    "the link below to reset your password.")
            body += '<a href="%s">%s</a>' % (url, url)
            sender = '易多云 客户支持 <support@eduoyun.com>'
            send_email.delay(sender, recipients, subject, body)
            response = ('Password reset link sent to your mailbox,'
                        ' it will be valid for the next 24 hours')
        else:
            message = 'This email does not exist'

    return render_template("user/pwreset.html",
                           message=message,
                           response=response,
                           email=email)


@bp.route("/pwreset/<token>", methods=["GET", "POST"])
def pwreset_change(token):
    user_id = user_api.validate_pwreset_token(token)
    message = ''
    if user_id is None:
        message = "url invalid"
    elif 'change_password' in request.form:
        new_password = request.form['password']
        user_api.reset_password(user_id, new_password)
        message = 'Password changed'
    return render_template("user/pwreset_change.html",
                           message=message)

uni/templates/site/cart.html
{% extends "site/layout.html" %}
{% block title %}购物车 - 易多云{% endblock %}
{% block content %}
  <h3>购物车</h3>
  <hr />
  <div class="row">
    <div class="span8">
      <form method="POST" action="" class="form-horizontal validate-form">
        <table class="table table-striped">
          <thead>
            <tr>
              <th colspan="3">产品</th>
              <th>价格</th>
              <th>优惠</th>
            </tr>
          </thead>
          <tbody>
            {% if products %}
              {% for product in products %}
                <tr>
                  <td>
                    <span class="product" name="{{ product.name }}" product_id="{{ product.product_id }}" type="{{ product.type }}" item_id="{{ product.item_id }}" term="{{ product.term }}">{{ _(product.name) }} {{ _(product.type) }}</span>
                  </td>
                  <td class="term"><select name="{{ product.name }}">
                      {% for price in product.prices %}
                        <option price="{{ price.price }}" discount="{{ price.discount }}" term="{{ price.term }}" value="{{ price.term }}" {% if product.term == price.term %}selected="selected"{% endif %}>{{
                        _(price.term) }}</option>
                      {% endfor %}
                  </select></td>
                  <td class="cart-delete"><span class="btn btn-info">删除</span></td>
                  <td class="price">{{ product.current_price }}</td>
                  <td class="discount">{{ product.current_discount }}</td>
                </tr>
              {% endfor %}
            {% else %}
              <tr><td colspan="5">购物车无物品</td><tr>
                {% endif %}
              </tbody>
              <tfoot>
                <tr>
                  <td colspan="3"><strong>总计</strong></td>
                  <td colspan="2" id="total"></td>
                </tr>
              </tfoot>
            </table>
            {% if products %}
              {% if not g.user %}
                <div class="well">
                  <p style="margin-left:180px">会员注册信息</p>
                  {% if message %}
                    <p class="alert alert-error" style="margin-left:180px;width:170px;">{{ _(message) }}</p>
                  {% endif %}
                  {{ signup_form.csrf_token }}
                  {{ render_form(signup_form.username) }}
                  {{ render_form(signup_form.password) }}
                  {{ render_form(signup_form.confirm) }}
                  <div class="control-group" style="margin-bottom:0">
                    <div class="controls">
                      <p>已经有账号，<a href="https://{{ request.host }}{{ url_for("user.login") }}?next=https://{{ request.host }}{{ url_for("cart") }}">立即登陆</a></p>
                    </div>
                  </div>
                </div>
              {% else %}
              {% if contact_required %}
                <div class="well">
                  <div id="existing-contact">
                    <h4 style="margin-bottom:20px;">域名注册需要联系方式:</h4>
                      <input type="hidden" name="contact_submitted"/>
                    {% if not contacts or new_contact %}
                      <input type="hidden" name="new_contact"/>
                      {{ contact_form.csrf_token }}
                      {{ render_form(contact_form.name) }}
                      {{ render_form(contact_form.company) }}
                      {{ render_form(contact_form.contact_email) }}
                      {{ render_form(contact_form.telephone) }}
                      <div class="control-group">
                        <div class="controls">
                          <select id="country" name="country" style="width:80px;">
                            {% for country in COUNTRY %}
                              <option value="{{ country.cn }}">{{ country.cn }}</option>
                            {% endfor %}
                          </select>
                          <select id="province" class="required" name="province" style="width:110px;">
                            <option value="">-请选择省份-</option>
                            {% for province_item in PROVINCE %}
                              <option value="{{ province_item.cn }}" {% if province_item.cn == province %}selected{% endif %}>{{ province_item.cn }}</option>
                            {% endfor %}
                          </select>
                        </div>
                      </div>
                      {{ render_form(contact_form.address) }}
                      {{ render_form(contact_form.postcode) }}
                    {% else %}
                      {% for contact in contacts %} 
                        <label class="radio">
                          <input type="radio" name="choose_contact" value="{{ contact.id }}" checked>
                          {{ contact.name }} {{ contact.company }} {{ contact.email }} {{ contact.telephone }} {{ contact.country }} {{ contact.province }} {{ contact.city }} {{ contact.address }} {{ contact.postcode }}
                        </label>
                      {% endfor %}
                      <a id="create-contact" href="#">或者添加新地址</a>
                    {% endif %}
                  </div>
                </div>
              {% endif %}
              {% endif %}
              <label style="display:inline;" class="checkbox">
                {{ signup_form.accept_tos(style="margin: 8px -10px 0 10px;") }}
                {% if signup_form.accept_tos.errors %}
                  {% for error in signup_form.accept_tos.errors %}
                    <span class="help-inline" {% if signup_form.accept_tos.errors %}style="color: #b94a48;"{% endif %}>{{ _(error) }}</span>
                  {% endfor %}
                {% endif %}
                <span>我已阅读并接受<a href="{{ url_for('tos') }}">用户协议</a></span>
              </label>
              <input id="checkout" type="submit" name="checkout" class="btn btn-primary" style="margin-left: 20px;" value="结算" {% if not products %}disabled="disabled"{% endif %} />
            {% endif %}
          </form>
        </div>
        <div class="span4">
          <form method="POST">
            {% if voucher %}
              <input type="submit" name="cancel_voucher" id="cancel_voucher" class="btn btn-primary" value="取消使用该优惠券" />
              <p class="alert alert-info" style="margin-top:8px">已使用优惠券：{{ voucher.name }}</p>
            {% else %}
              <input type="text" name="voucher" id="voucher" value="" style="width: 150px;" />
              <input type="submit" name="update_voucher" id="update_voucher" class="btn btn-primary" value="使用优惠券" style="margin-bottom:8px;" />
              {% if response %}
                <p class="alert alert-error">{{ _(response) }}</p>
              {% endif %}
            {% endif %}
          </form>
          {% if g.user %}
            <div class="well">
              <p>已登陆为 {{ g.user.username }}</p>
              <p>不是此账号，<a href="{{ url_for('user.logout', next=url_for('cart')) }}">点此登出</a></p>
            </div>
          {% endif %}
        </div>
      </div>
    {% endblock %}

uni/templates/site/contact.html
{% extends "site/layout.html" %}
{% block title %}联系我们 - 易多云{% endblock %}
{% block contact %}class="active"{% endblock %}
{% block content %}
<h3>联系我们</h3>

<p>
电话:<br />
<i class="icon icon-headphones"></i> 021-61037440
</p>


<p>客服E-mail:<br />
<i class="icon icon-envelope"></i> <a href="mailto:support@eduoyun.com">support@eduoyun.com</a>
</p>

<p>
客服QQ:<br />
<i class="icon icon-user"></i> <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2640842721&site=qq&menu=yes">2640842721</a>
</p>

<p>
关注我们:<br />
<i class="icon icon-edit"></i> <a href="http://www.weibo.com/2914576497" target="_blank">新浪微博</a>
</p>

<p>
在线客服:<br />
<i class="icon icon-comment"></i> <a href="javascript:void(0);" onclick="olark('api.box.expand')">请点击右下角在线客服</a>
</p>

<p>
地址:<br />
<i class="icon icon-briefcase"></i> 上海市南京西路1515号静安嘉里中心一座29楼
</p>

<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://ditu.google.cn/maps?f=q&amp;source=s_q&amp;hl=zh-CN&amp;geocode=&amp;q=%E4%B8%8A%E6%B5%B7%E9%9D%99%E5%AE%89%E5%98%89%E9%87%8C%E4%B8%AD%E5%BF%83&amp;aq=&amp;sll=31.224305,121.450537&amp;sspn=0.001901,0.004128&amp;brcurrent=3,0x35b27002cd47a7f1:0x57b3bfb932aaf682,0%3B5,0,0&amp;ie=UTF8&amp;hq=%E4%B8%8A%E6%B5%B7%E9%9D%99%E5%AE%89%E5%98%89%E9%87%8C%E4%B8%AD%E5%BF%83&amp;t=m&amp;ll=31.228693,121.449351&amp;spn=0.012844,0.018239&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="http://ditu.google.cn/maps?f=q&amp;source=embed&amp;hl=zh-CN&amp;geocode=&amp;q=%E4%B8%8A%E6%B5%B7%E9%9D%99%E5%AE%89%E5%98%89%E9%87%8C%E4%B8%AD%E5%BF%83&amp;aq=&amp;sll=31.224305,121.450537&amp;sspn=0.001901,0.004128&amp;brcurrent=3,0x35b27002cd47a7f1:0x57b3bfb932aaf682,0%3B5,0,0&amp;ie=UTF8&amp;hq=%E4%B8%8A%E6%B5%B7%E9%9D%99%E5%AE%89%E5%98%89%E9%87%8C%E4%B8%AD%E5%BF%83&amp;t=m&amp;ll=31.228693,121.449351&amp;spn=0.012844,0.018239&amp;z=15&amp;iwloc=A" style="color:#0000FF;text-align:left">查看大图</a></small>

{% endblock %}

uni/templates/site/faq.html
{% extends "site/layout.html" %}
{% block title %}常见问题 - 易多云{% endblock %}
{% block faq %}class="active"{% endblock %}
{% block content %}
<div class="accordion">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse1">
        1. 虚拟主机的架构是什么，支持哪些语言？
      </a>
    </div>
    <div id="collapse1" class="accordion-body collapse">
      <div class="accordion-inner">
        流行的LAMP架构，操作系统为CentOS，采用Apache，数据库为MySQL，支持PHP，Python，Perl，Ruby on Rails (RoR)，CGI。
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse2">
        2. 一键安装网站程序是指什么？
      </a>
    </div>
    <div id="collapse2" class="accordion-body collapse" style="height: 0px; ">
      <div class="accordion-inner">
        这是我们提供的一个功能，可以自动安装一些优秀的开源网站，例如Wordpress，Drupal，phpWind，Magento等等，一键安装是指能够自动创建好所需的数据库，设置好配置文件，不需要用户手动操作即可搭建起网站，方便快捷。
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse3">
        3. 你们的Ruby on Rails (RoR)部署是如何实现的？
      </a>
    </div>
    <div id="collapse3" class="accordion-body collapse">
      <div class="accordion-inner">
        通过Passenger实现，我们可以提供免费的部署支持。
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse4">
        4. 你们的CGI程序需要放到特定的文件夹吗，例如cgi-bin？
      </a>
    </div>
    <div id="collapse4" class="accordion-body collapse">
      <div class="accordion-inner">
        不需要，你可以放在网站的任何位置，都可以生效。
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse5">
        5. 我想把现有的网站搬到你们的虚拟主机，你们可以帮我进行数据迁移吗？
      </a>
    </div>
    <div id="collapse5" class="accordion-body collapse">
      <div class="accordion-inner">
        完全可以，我们帮你迁移之后测试一切正常，你再修改DNS，保证网站一秒也不当机。
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse6">
    6. 需要备案吗？
      </a>
    </div>
    <div id="collapse6" class="accordion-body collapse">
      <div class="accordion-inner">
        不需要，虚拟主机架设在Amazon海外机房，你的网站可以即时上线，无须备案。
      </div>
    </div>
  </div>
</div>
<p>不确定是不是你想要的？</p>
{{ link_to("hosting.trial", "立即免费试用", class="btn", secure=true) }}

{% endblock %}

uni/templates/site/invoice.html
{% extends "site/layout.html" %}
{% block title %}订单确认 - 易多云{% endblock %}
{% block content %}
<h3>确认订单</h3>
<hr />
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>产品</th>
      <th>时长</th>
      <th>金额</th>
      <td>优惠</td>
    </tr>
  </thead>
  <tbody>
    {% for item in items %}
    <tr>
      <td>{{ _(item.product) }} {{ _(item.type) }}</td>
      <td>{{ _(item.term) }}</td>
      <td>{{ item.amount }}</td>
      <td>{{ item.discount }}</td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2">总计</td>
      <td colspan="2">{{ total_amount }}</td>
    </tr>
  </tfoot>
</table>
<form method="POST" target="_blank">
  <input style="display:none;" type="text" name="pay" value="" />
  <input type="submit" name="" id="pay" class="btn btn-primary" value="用支付宝购买" />
</form>
<a id="payment" href="#payment_info" style="display:none;" data-toggle="modal"></a>
<div class="modal hide" id="payment_info">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3>登陆到支付宝付款</h3>
  </div>
  <div class="modal-header">
    <p>请在新开支付宝页面完成付款后选择:</p>
    <br />
    <p>付款成功：<a href="{{url_for('user.invoices')}}">查看账单</a></p>
    <p>付款失败：<a href="{{url_for('user.invoices_show', invoice_id=invoice_id)}}">重新付款</a></p>
  </div>
  <div class="modal-footer">
  </div>
</div>
{% endblock %}

uni/templates/site/layout.html
{% from "site/helpers.html" import render_form, link_to with context %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    {% block css %}{% endblock %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/logo/favicon.ico') }}" />
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.validate.js') }}"></script>
    {% block js %}{% endblock %}
  </head>
  <body>
    <div class="navbar navbar-static-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="{{ url_for('index') }}"><div id="logo"></div></a>
          <ul class="nav nav-pills">
            <li {% block index %}{% endblock %}>{{ link_to("index", "首  页", secure=false) }}</li>
            <li {% block hosting %}{% endblock %}>{{ link_to("hosting.index", "虚拟主机", secure=false) }}</li>
            <li {% block domain %}{% endblock %}>{{ link_to("domain.index", "域 名", secure=true) }}</li>
            <li {% block faq %}{% endblock %}>{{ link_to("http://help.eduoyun.com/", "帮助中心", secure=false, external=True) }}</li>
            <li {% block contact %}{% endblock %}>{{ link_to("contact", "联系我们", secure=false) }}</li>
          </ul>
          {% block user %}
            <ul class="nav nav-pills pull-right">
              <li>{{ link_to("user.index", "会员中心", secure=true) }}</li>
            </ul>
          {% endblock %}
        </div>
      </div>
    </div>
    {% if g.user and g.user.group == 'admin' %}
      <div id="admin-link">
        <a href="https://{{ request.host }}{{ url_for('admin.index') }}">
          <div class="alert alert-success">
            管<br />理<br />中<br />心
          </div>
        </a>
      </div>
    {% endif %}
    <div class="container" style="margin-top: 30px;">
      {% block content %}{% endblock %}
      <hr>
      <footer>
      <p>易多云&copy;2012&nbsp;版权所有</p>
      </footer>
    </div>

    <!-- begin olark code --><script data-cfasync="false" type='text/javascript'>/*{literal}<![CDATA[*/
      window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){f[z]=function(){(a.s=a.s||[]).push(arguments)};var a=f[z]._={},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={0:+new Date};a.P=function(u){a.p[u]=new Date-a.p[0]};function s(){a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{b.contentWindow[g].open()}catch(w){c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{var t=b.contentWindow[g];t.write(p());t.close()}catch(x){b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
      /* custom configuration goes here (www.olark.com/documentation) */
      olark.identify('6115-295-10-1782');/*]]>{/literal}*/</script><noscript><a href="https://www.olark.com/site/6115-295-10-1782/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript><!-- end olark code -->
    {% if g.user %}
      <script type="text/javascript"> olark('api.chat.updateVisitorNickname', { 
        snippet: "{{g.user.username}}" 
        }); 
      </script>
    {% endif %}

  </body>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-31931843-1']);
    _gaq.push(['_setDomainName', 'eduoyun.com']);
    _gaq.push(['_trackPageview']);

    (function() {
     var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
     ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();

   </script>
 </html>