uni/views/user/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint, flash, request, redirect, url_for
from flask import g, render_template
from flask.ext.login import login_required, login_user, logout_user
from flask.ext.babel import gettext as _
from uni import user, invoice, login_manager
from uni.tasks import send_email
from uni.forms import SignupForm, LoginForm, PasswordChangeForm

bp = Blueprint('user', __name__, url_prefix='/user')
user_api = user.API()
invoice_api = invoice.API()


@login_manager.user_loader
def load_user(user_id):
    return user_api.load_user(user_id)


@bp.route('/')
@login_required
def index():
    username = g.user.username
    unpaid_invoices = invoice_api.get_unpaid_invoices_by_user(username)
    return render_template('user/index.html',
                           unpaid_invoices=unpaid_invoices)


@bp.route('/login', methods=["GET", "POST"])
def login():
    if g.user is not None:
        return redirect("https://%s%s" % (request.host, url_for("user.index")))

    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember_me = form.remember_me.data

        user = user_api.validate(username, password)
        if user:
            login_user(user_api.load_user(user['id']), remember=remember_me)
            return redirect(request.args.get("next") or "https://%s%s" %
                            (request.host, url_for("user.index")))
        else:
            flash('Failed login', 'error')

    return render_template('user/login.html',
                           form=form)


@bp.route('/signup', methods=["GET", "POST"])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = user_api.get_by_username(username)
        if user:
            flash("Username already exists", "error")
        else:
            user = user_api.create(username, password)
            login_user(user_api.load_user(user['id']))
            return redirect("https://%s%s" %
                            (request.host, url_for("user.index")))

    return render_template('user/signup.html',
                           form=form)


@bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(request.args.get("next") or "http://%s%s" %
                    (request.host, url_for("index")))


@bp.route("/invoices/")
@login_required
def invoices():
    username = g.user.username
    invoices = invoice_api.get_invoices_by_user(username)
    return render_template("user/invoices.html",
                           invoices=invoices)


@bp.route("/invoices/<invoice_id>")
@login_required
def invoices_show(invoice_id):
    invoice_id = int(invoice_id)
    username = g.user.username
    invoice = invoice_api.validate_by_user(username, invoice_id)
    if not invoice:
        return redirect(url_for("user.invoices"))

    invoice_items = invoice_api.get_items_by_invoice_id(invoice_id)
    total_amount = 0
    for invoice_item in invoice_items:
        total_amount += invoice_item['amount']
    return render_template("user/invoices_show.html",
                           total_amount=total_amount,
                           invoice_items=invoice_items,
                           invoice=invoice)


@bp.route("/password", methods=["GET", "POST"])
@login_required
def password():
    username = g.user.username
    message = ''
    form = PasswordChangeForm()
    if form.validate_on_submit():
        original_password = request.form['original_password']
        new_password = form.password.data
        message = user_api.change_password(username,
                                           original_password,
                                           new_password)
    return render_template("user/password.html",
                           message=message,
                           form=form)


@bp.route("/pwreset/", methods=["GET", "POST"])
def pwreset():
    email = ''
    message = ''
    response = ''
    if 'submit' in request.form:
        email = request.form['email']
        user = user_api.get_by_username(email)
        if user:
            token = user_api.create_pwreset_token(user['id'])
            subject = _("password reset - yiduoyun")
            recipients = [email]
            url = "https://%s%s%s" % (request.host,
                                      url_for("user.pwreset"),
                                      token)
            body = "<p>%s,</p>" % _("Dear Customer")
            body += "<p>%s</p>" % _("You submitted a password reset request "
                                    "recently. If you did not, please ignore "
                                    "this meesage. If you do, please click "
                                    "the link below to reset your password.")
            body += '<a href="%s">%s</a>' % (url, url)
            sender = '易多云 客户支持 <support@eduoyun.com>'
            send_email.delay(sender, recipients, subject, body)
            response = ('Password reset link sent to your mailbox,'
                        ' it will be valid for the next 24 hours')
        else:
            message = 'This email does not exist'

    return render_template("user/pwreset.html",
                           message=message,
                           response=response,
                           email=email)


@bp.route("/pwreset/<token>", methods=["GET", "POST"])
def pwreset_change(token):
    user_id = user_api.validate_pwreset_token(token)
    message = ''
    if user_id is None:
        message = "url invalid"
    elif 'change_password' in request.form:
        new_password = request.form['password']
        user_api.reset_password(user_id, new_password)
        message = 'Password changed'
    return render_template("user/pwreset_change.html",
                           message=message)

uni/views/user/domain/__init__.py
import json
from functools import wraps
from flask import Blueprint, render_template, g, redirect, url_for, jsonify
from flask import request
from flask.ext.login import login_required
from flask.ext.babel import gettext as _

from uni import province, country
from uni.domain import API
from uni.forms import ContactForm
from uni.views.site import add_contact

domain_api = API()
PROVINCE = province.PROVINCE
COUNTRY = country.COUNTRY

bp = Blueprint('user.domain', __name__, url_prefix='/user/domain')


def domain_required(f):
    @wraps(f)
    def decorated_function(domain_id, *args, **kwargs):
        domain = domain_api.get_domain_by_id_and_username(domain_id,
                                                          g.user.username)
        if domain is None or domain['status'] != 'active':
            return redirect(url_for('user.domain.index'))
        else:
            return f(domain, *args, **kwargs)
    return decorated_function


@bp.route('/')
@login_required
def index():
    username = g.user.username
    domains = domain_api.get_domains_by_username(username)
    return render_template("user/domain/index.html",
                           domains=domains)


@bp.route('/<domain_id>')
@login_required
@domain_required
def show(domain):
    domains = domain_api.get_domains_by_username(g.user.username)
    domains_list = json.dumps(
        [{"name": "%s.%s" % (d['name'], d['tld']),
          "id": d['id'], }
         for d in domains]
    )
    return render_template("user/domain/show.html",
                           domains=domains,
                           domains_list=domains_list,
                           domain=domain)


@bp.route('/<domain_id>/dns')
@login_required
@domain_required
def dns(domain):
    dns = domain_api.get_dns_by_domain_id(domain['id'])
    return render_template("user/domain/dns.html",
                           dns=dns,
                           domain=domain)


def translate_resp(request, resp, values):
    if 'msg' in resp:
        resp['message'] = resp['msg']
    if 'message' in resp:
        message = resp['message']
        mapping = {}
        invalid = {'IP address': 'content',
                   'name': 'hostname',
                   'cname': 'cname',
                   'ttl': 'ttl',
                   'priority': 'priority', }
        for key, value in invalid.items():
            if "Invalid %s" % key in message:
                message = resp['message'].replace(values[value],
                                                  '%s(%s)s' % ('%', value))
                mapping.update({value: values[value]})
        translated_message = _(message, **mapping)
        if translated_message != message % (mapping):
            resp['message'] = translated_message
        else:
            resp['message'] = _('Unknown Error')
            print '------------------------- un-translated ----------------'
            print message
            # and should notify

    return resp


@bp.route('/<domain_id>/add_dns', methods=["POST"])
@login_required
@domain_required
def add_dns(domain):
    hostname = request.form.get('hostname', '@').lower().strip()
    type = request.form.get('type', '')
    content = request.form.get('content', '').lower().strip()
    priority = request.form.get('priority', '').lower().strip()
    ttl = request.form.get('ttl', '').lower().strip()
    values = {'hostname': hostname,
              'type': type,
              'content': content,
              'priority': priority,
              'ttl': ttl, }

    resp = domain_api.add_dns(domain['id'], hostname, type,
                              content, priority, ttl)
    return jsonify(translate_resp(request, resp, values))


@bp.route('/<domain_id>/modify_dns', methods=["POST"])
@login_required
@domain_required
def modify_dns(domain):
    hostname = request.form.get('hostname', '@').lower().strip()
    type = request.form.get('type', '')
    content = request.form.get('content', '').lower().strip()
    priority = request.form.get('priority', '').lower().strip()
    ttl = request.form.get('ttl', '').lower().strip()
    record_id = request.form.get('record_id')
    values = {'hostname': hostname,
              'type': type,
              'content': content,
              'priority': priority,
              'ttl': ttl, }

    resp = domain_api.modify_dns(domain['id'], record_id,
                                 hostname, type, content, priority, ttl)
    return jsonify(translate_resp(request, resp, values))


@bp.route('/<domain_id>/delete_dns', methods=["POST"])
@login_required
@domain_required
def delete_dns(domain):
    record_id = request.form.get('record_id')
    resp = domain_api.delete_dns(domain['id'], record_id)
    return jsonify(translate_resp(request, resp, {}))


@bp.route('/<domain_id>/ns', methods=["GET", "POST"])
@login_required
@domain_required
def ns(domain):
    default_ns = domain_api.get_default_ns()
    resp = None
    if 'update-ns' in request.form:
        new_ns = request.form.getlist('ns')
        new_ns = [ns.lower().strip() for ns in new_ns if ns.lower().strip()]
        new_ns.sort()
        resp = domain_api.update_ns(domain['id'], new_ns)
    if 'reset-ns' in request.form:
        resp = domain_api.update_ns(domain['id'], default_ns)

    domain = domain_api.get_domain_by_id(domain['id'])
    ns = json.loads(domain['ns'])
    glue = domain_api.get_glue(domain['id'])
    return render_template("user/domain/ns.html",
                           ns=ns,
                           default_ns=default_ns,
                           resp=resp,
                           glue=glue,
                           domain=domain)


@bp.route('/<domain_id>/add_glue', methods=["POST"])
@login_required
@domain_required
def add_glue(domain):
    hostname = request.form.get('hostname', '').lower().strip()
    ip = request.form.get('ip', '').lower().strip()
    values = {'hostname': hostname,
              'ip': ip, }

    resp = domain_api.add_glue(domain['id'], hostname, ip)
    return jsonify(translate_resp(request, resp, values))


@bp.route('/<domain_id>/modify_glue', methods=["POST"])
@login_required
@domain_required
def modify_glue(domain):
    hostname = request.form.get('hostname', '').lower().strip()
    ip = request.form.get('ip', '').lower().strip()
    glue_id = request.form.get('glue_id')
    values = {'hostname': hostname,
              'type': type, }
    resp = domain_api.modify_glue(domain['id'], glue_id, hostname, ip)
    return jsonify(translate_resp(request, resp, values))


@bp.route('/<domain_id>/delete_glue', methods=["POST"])
@login_required
@domain_required
def delete_glue(domain):
    glue_id = request.form.get('glue_id')
    resp = domain_api.delete_glue(domain['id'], glue_id)
    return translate_resp(request, resp, {})


@bp.route('/<domain_id>/contact', methods=["GET", "POST"])
@login_required
@domain_required
def contact(domain):
    message = None
    form = ContactForm()
    create_contact = False
    if 'confirm-create-contact' in request.form:
        if not form.validate_on_submit():
            create_contact = True
        else:
            resp = add_contact(g.user.id, form,
                               create_resellbiz=True)
            if resp['status'] == 'failed':
                msg = _(resp['message'])
                if msg == resp['message']:
                    print resp['message']
                    msg = _('Contact created failed')
                    # should notify
                message = {'severity': 'error',
                           'msg': msg, }
            else:
                message = {
                    'severity': 'success',
                    'msg': _('Contact created successfully'),
                }

    if 'change-contact' in request.form:
        reg_contact = request.form.get('reg-contact')
        admin_contact = request.form.get('admin-contact')
        tech_contact = request.form.get('tech-contact')
        billing_contact = request.form.get('billing-contact')
        resp = domain_api.change_contact(domain['id'], reg_contact,
                                         admin_contact,
                                         tech_contact, billing_contact)
        if resp['status'] != 'success':
            msg = _(resp['message'])
            if msg == resp['message']:
                msg = _('Contact changed failed')
            message = {'severity': 'error',
                       'msg': msg, }
        else:
            message = {
                'severity': 'success',
                'msg': _('Contact changed successfully'),
            }

    domain = domain_api.get_domain_by_id(domain['id'])
    contacts = domain_api.get_contacts_by_username(g.user.username)
    return render_template("user/domain/contact.html",
                           contacts=contacts,
                           message=message,
                           form=form,
                           create_contact=create_contact,
                           city=request.form.get('city'),
                           province=request.form.get('province'),
                           country=request.form.get('country'),
                           PROVINCE=PROVINCE,
                           COUNTRY=COUNTRY,
                           domain=domain)

uni/templates/user/index.html
{% extends "user/layout.html" %}
{% block title %}会员中心 - 易多云{% endblock %}
{% block user_index %}class="active"{% endblock %}
{% block user_content %}
<p>登陆邮箱: {{ g.user.username }}</p>
<p><a class="btn" href="{{ url_for("user.invoices") }}">查看所有账单</a><a style="margin-left: 10px;" class="btn" href="{{ url_for("user.password") }}">修改密码</a></p>
<hr />
<p>未付款账单</p>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>    
        <th>账单编号</th>
        <th>创建时间</th>
        <th>总计</th>
        <th>状态</th>
        <th>付款时间</th>
        <th></th>
      </tr>
      </thead>
        <tbody>
          {% for invoice in unpaid_invoices %}
          <tr>
            <td>{{ invoice.uuid }}</td>
            <td>{{ invoice.created_at }}</td>
            <td>{{ invoice.amount }}</td>
            <td>{% if invoice.paid %}已付款{% else %}未付款{% endif %}</td>
            <td>{% if invoice.paid_at %}{{ invoice.paid_at }}{% endif %}</td>
            <td><a href="{{ url_for("user.invoices_show", invoice_id = invoice.id) }}" class="btn">查看账单</a>{% if not invoice.paid %}<br /><a href="https://{{ request.host }}/invoice/{{ invoice.id }}" style="margin-top:3px" class="btn btn-primary">现在付款</a>{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

uni/templates/user/invoices.html
{% extends "user/layout.html" %}
{% block title %}账单 - 易多云{% endblock %}
{% block user_invoices %} active{% endblock %}
{% block breadcrumb %}
<span class="divider">/</span>
<li class="active">账单</li>
{% endblock %}
{% block user_content %}
<h3>我的账单</h3>
<table class="table table-striped table-bordered">
  <thead>
    <tr>    
      <th>账单编号</th>
      <th>创建时间</th>
      <th>总计</th>
      <th>状态</th>
      <th>付款时间</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for invoice in invoices %}
    <tr>
      <td>{{ invoice.uuid }}</td>
      <td>{{ invoice.created_at }}</td>
      <td>{{ invoice.amount }}</td>
      <td>{% if invoice.paid %}已付款{% else %}未付款{% endif %}</td>
      <td>{% if invoice.paid_at %}{{ invoice.paid_at }}{% endif %}</td>
      <td><a href="{{ url_for("user.invoices_show", invoice_id = invoice.id) }}" class="btn">查看账单</a>{% if not invoice.paid %}<br /><a href="{{url_for('invoice', invoice_id=invoice.id)}}" style="margin-top:3px" class="btn btn-primary">现在付款</a>{% endif %}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

uni/templates/user/invoices_show.html
{% extends "user/layout.html" %}
{% block title %}账单 - 易多云{% endblock %}
{% block user_invoices %} active{% endblock %}
{% block breadcrumb %}
<span class="divider">/</span>
<li>
<a href="{{url_for('user.invoices')}}/user/invoices">账单</a> 
</li>
<span class="divider">/</span>
<li class="active">{{ invoice.uuid }}</li>
{% endblock %}
{% block user_content %}
<h3>账单 {{ invoice.uuid }}</h3>
{% if invoice.paid %}
<p>已付款</p>
{% else %}
<p>未付款</p>
<a href="{{url_for('invoice', invoice_id=invoice.id)}}" style="margin-top:3px" class="btn btn-primary">现在付款</a>
{% endif %}
<hr />
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>产品</th>   
      <th>时长</th>
      <th>数额</th>
      <th>优惠</th>
    </tr>
  </thead>
  <tbody>
    {% for invoice_item in invoice_items %}
    <tr>
      <td>{{ _(invoice_item.product) }} {{ _(invoice_item.type) }}</td>
      <td>{{ _(invoice_item.term) }}</td>
      <td>{{ invoice_item.amount }}</td>
      <td>{{ invoice_item.discount }}</td>
    </tr>  
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2">总计</td>
      <td colspan="2">{{ total_amount }}</td>
    </tr>
  </tfoot>
</table>
{% endblock %}

uni/templates/user/layout.html
{% extends "site/layout.html" %}
{% block user %}
<ul class="nav nav-pills pull-right">
  <li class="account"><a>{{g.user.username}}</a></li>
  <li class="divider-vertical"></li>
  <li class="dropdown" id="menu1">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">账户<b class="caret"></b></a>
  <ul class="dropdown-menu">
      <li><a href="{{ url_for("user.logout") }}">登出</a></li>
  </ul>
  </li>
</ul>
{% endblock %}

{% block content %}
<div class="row">
  <div class="span3 columns">
    <div class="well">
      <ul class="nav nav-pills nav-stacked">
        <li {% block user_index %}{% endblock %}>{{ link_to("user.index", "会员中心") }}</li>
        <li class="indent {% block user_invoices %}{% endblock %}"><a href="{{ url_for("user.invoices") }}">查看账单</a></li>
        <li class="indent {% block user_password %}{% endblock %}"><a href="{{ url_for("user.password") }}">修改密码</a></li>

        <li {% block user_domain_active %}{% endblock %}> <a href="{{url_for('user.domain.index')}}">域名管理</a></li>
        {% if domain %}
        <li class="indent {% block user_domain_id %}{% endblock %}"> 
        <a href="{{url_for('user.domain.show', domain_id=domain.id)}}">域名管理菜单</a>
        </li>
        <li class="indent {% block user_domain_id_dns %}{% endblock %}">
        <a href="{{url_for('user.domain.dns', domain_id=domain.id)}}">域名解析(DNS)</a>
        </li>
        <li class="indent {% block user_domain_id_ns %}{% endblock %}">
        <a href="{{url_for('user.domain.ns', domain_id=domain.id)}}">域名服务器(NS)</a>
        </li>
        <li class="indent {% block user_domain_id_contact %}{% endblock %}">
        <a href="{{url_for('user.domain.contact', domain_id=domain.id)}}"> 联系方式</a>
        </li>
        {% endif %}
        <li {% block user_hosting_active %}{% endblock %}> <a href="{{url_for('user.hosting.index')}}">虚拟主机管理</a></li>
        {% if hosting and hosting.status == 'active' %}
        <li class="indent{% block user_hosting_websites_active %}{% endblock %}"> 
        <a href="{{url_for('user.hosting.websites')}}">网站绑定</a>
        </li>
        <li class="indent{% block user_hosting_ftp_active %}{% endblock %}"> 
        <a href="{{url_for('user.hosting.ftpusers')}}">FTP账户</a>
        </li>
        <li class="indent{% block user_hosting_mysqlusers_active %}{% endblock %}"> 
        <a href="{{url_for('user.hosting.mysqlusers')}}">MySQL账户</a>
        </li>
        </li>
        <li class="indent{% block user_hosting_mysqldbs_active %}{% endblock %}"> 
        <a href="{{url_for('user.hosting.mysqldbs')}}">MySQL数据库</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
  <div class="span9 columns">
    <ul class="breadcrumb">
      <li>
      <a href="{{url_for('user.index')}}">会员中心</a> 
      </li>
      {% block breadcrumb %}
      {% endblock %}
    </ul>
    {% block user_content %}
    {% endblock %}
  </div>
</div>
{% endblock %}
<a href="#"></a> <span class="divider">/</span>

uni/templates/user/login.html
{% from "site/helpers.html" import render_form, flash_messages, link_to with context %}
{% extends "site/layout.html" %}
{% block title %}会员登陆 - 易多云{% endblock %}
{% block content %}
  <div class="row">
    <div class="span8">
      <h3>您需要先登录才能继续操作</h3>
      <hr />
      <p>还没有账号，{{ link_to("user.signup", "立即注册") }}</p>
    </div>
    <div class="span4">
      <form method="POST" class="well">
        <fieldset>
          <legend>用户登录</legend>
          {{ flash_messages() }}
          {{ form.csrf_token }}
          {{ render_form(form.username, type="basic", style="width: 245px;") }}
          {{ render_form(form.password, type="basic", style="width: 245px;") }}
          <label class="checkbox">
            {{ form.remember_me }}
            记住我 
          </label>
          <br />
          <input class="btn btn-primary" type="submit" value="登录" name="login" />
          {{ link_to("user.pwreset", "忘记密码", class="btn") }}
        </fieldset>
      </form>
    </div>
  </div>
{% endblock %}

uni/templates/user/password.html
{% extends "user/layout.html" %}
{% block title %}修改密码 - 易多云{% endblock %}
{% block user_password %} active{% endblock %}
{% block breadcrumb %}
<span class="divider">/</span>
<li class="active">修改密码</li>
{% endblock %}
{% block user_content %}
{% if message == 'Password changed' %}
<p class="alert alert-success">成功修改密码</p>
{% else %}
    <form method="POST" class="form-horizontal validate-form">
      <fieldset>
        <div class="control-group">
          <div class="controls">
            <h3>修改密码</h3>          
          </div>
        </div>
            {% if message %}
            <p class="alert alert-error">{{ _(message) }}</p>
            {% endif %}
        <div class="control-group">
          <label class="control-label" for="original_password">原密码:</label>
          <div class="controls">
            <input type="password" class="input-large" id="original_password" name="original_password" value="{{ original_password }}"  >
            <p class="help-block">请输入你原来的密码</p>
          </div>
        </div>
        {{ form.csrf_token }}
        {{ render_form(form.password) }}
        {{ render_form(form.confirm) }}
        <div class="form-actions">
          <input class="btn btn-success" type="submit" value="确认修改" name="change_password" />
        </div>
      </fieldset>
    </form>
    {% endif %}
{% endblock %}

uni/templates/user/pwreset.html
{% extends "site/layout.html" %}
{% block title%}找回密码 - 易多云{% endblock %}
{% block content %}
  <h3>找回密码</h3>
  {% if response %}
    <p class="alert alert-success">{{ _(response) }}</p>
  {% else %}
    <form method="POST" class="form-horizontal validate-form">
      <fieldset>
        {% if message %}
          <p class="alert alert-error">{{ _(message) }}</p>
        {% endif %}
        <div class="control-group">
          <label class="control-label" for="input01">E-mail:</label>
          <div class="controls">
            <input type="text" class="input-large" id="email" name="email" value="{{ email }}" >
            <p class="help-block">请输入你注册时的E-mail地址，我们将会发送重置密码的链接到你的邮箱</p>
          </div>
        </div>
        <div class="form-actions">
          <input class="btn btn-success" type="submit" value="提交" name="submit" />
        </div>
      </fieldset>
    </form>
  {% endif %}
{% endblock %}

uni/templates/user/pwreset_change.html
{% extends "site/layout.html" %}
{% block title %}密码重置 - 易多云{% endblock %}
{% block content %}
{% if message == 'Password changed' %}
<p class="alert alert-success">成功修改密码</p>
{% elif message == 'url invalid' %}
<p class="alert alert-error">链接无效</p>
{% else %}
    <form method="POST" class="form-horizontal validate-form">
      <fieldset>
        <div class="control-group">
          <div class="controls">
            <h3>密码重置</h3>          
          </div>
        </div>
            {% if message %}
            <p class="alert alert-error">{{ message }}</p>
            {% endif %}
        <div class="control-group">
          <label class="control-label" for="password">密码:</label>
          <div class="controls">
            <input type="password" class="input-large" id="password" name="password" value="{{ password }}"  >
            <p class="help-block">请输入你想要重置的密码</p>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="password_confirm">确认密码:</label>
          <div class="controls">
            <input type="password" class="input-large" id="password_confirm" name="password_confirm" value="{{ password_confirm }}"  >
            <p class="help-block">请再次输入你的密码</p>
          </div>
        </div>
        <div class="form-actions">
          <input class="btn btn-success" type="submit" value="确认修改" name="change_password" />
        </div>
      </fieldset>
    </form>
    {% endif %}
{% endblock %}

uni/templates/user/signup.html
{% from "site/helpers.html" import render_form, flash_messages, link_to with context %}
{% extends "user/layout.html" %}
{% block title %}用户注册 - 易多云{% endblock %}
{% block content %}
  <div class="row">
    <div class="span8">
      <form method="POST" class="form-horizontal">
        <fieldset>
          <legend>用户注册</legend>
          {{ flash_messages() }}
          {{ form.csrf_token }}
          {{ render_form(form.username) }}
          {{ render_form(form.password) }}
          {{ render_form(form.confirm) }}

          <div class="control-group {% if form.accept_tos.errors %}error{% endif %}">
            <div class="controls">
              <label class="checkbox">
                {{ form.accept_tos }}
                {% if form.accept_tos.errors %}
                  {% for error in form.accept_tos.errors %}
                    <span class="help-inline">{{ _(error) }}</span>
                  {% endfor %}
                {% endif %}
                同意遵守<a href="{{ url_for('tos') }}">用户协议</a> 
              </label>
            </div>
          </div>

          <div class="form-actions">
            <input class="btn btn-success" type="submit" value="注册" name="signup" />
          </div>
        </fieldset>
      </form>
    </div>
    <div class="span4">
      <p>已经有账号，{{ link_to("user.login", "立即登陆") }}</p>
    </div>
  </div>
{% endblock %}